"""Add column buzzer_activated

Revision ID: 1d9c4def14fc
Revises: 6bf085bb3dd7
Create Date: 2025-07-17 09:56:41.048707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9c4def14fc'
down_revision: Union[str, Sequence[str], None] = '6bf085bb3dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_lampu', sa.Column('buzzer_activated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_lampu', 'buzzer_activated')
    # ### end Alembic commands ###
